name: GitHub Metrics

on:
  schedule: [{ cron: "0 * * * *" }] # runs every hour
  push: { branches: ["main"] }     # also runs on push

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Plugins you want to enable
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_followup: yes
          plugin_lines: yes
          plugin_stargazers: yes
          plugin_habits: yes
          plugin_achievements: yes
